### PR TITLE
add info page

### PR DESCRIPTION
**Pull request by wave49192**

### CODE REVIEW

**Comment by tboonma** [comment]
Not sure why this ratio got some element out of window
Screen Shot 2565-11-08 at 13 54 41

## Step to reproduce
1. Go to [the service](https://voter-frontend-pv0m46yyj-voter.vercel.app/)
2. Resize the width of browser

**Review by bhokin — COMMENTED** [review]
In my opinion, the detail should show on the card to make it more convenient to compare the candidates.

**Comment by bhokin** [comment]
About the responsive of the card info, I think we can fix it in the future if you want to.

**Review by tboonma — APPROVED** [review]
LGTM

**Pull request merged**
