### PR TITLE
Fix register page

### PR DESCRIPTION
**Pull request by danyouknowme**
Create a hook to autofocus next input and create laser id information card component

### CODE REVIEW

**Comment by bhokin** [comment]
image
**Sign In / Sing Up** text in a sidebar is linked to the same page which is the sign-in page.

**Comment by danyouknowme** [comment]
> image **Sign In / Sing Up** text in a sidebar is linked to the same page which is the sign-in page.

Actually, I have no idea to design it

**Comment by danyouknowme** [comment]
> image **Sign In / Sing Up** text in a sidebar is linked to the same page which is the sign-in page.

solved

**Review by bhokin — APPROVED** [review]
👍🏻 👍🏻 👍🏻

**Pull request merged**
